Fixed possible division by 0 in L240-L245
code-423n4/2021-09-yaxis pull request #11
Opened 2021-09-21 11:27 UTC by GainsGoblin

Added a totalSupply() > 0 check.

2021-09-26 19:42 UTC, uN2RVw5q reviewed
I don't think this is necessary. This allows the following call to succeed:
1. `totalSupply()` is 0
2. `_shares` is `0`.

If both conditions are met, it does a net-zero transfer. I think it's okay to let it fail if `totalSupply()` is `0`.

2021-09-26 19:42 UTC, uN2RVw5q commented on contracts/v3/Vault.sol
> +            uint256 _amount = (balance().mul(_shares)).div(totalSupply());
```suggestion
        uint totalSupply = totalSupply();
        if (totalSupply > 0) {
            uint256 _amount = (balance().mul(_shares)).div(totalSupply);
```
Avoids a storage read.

2021-09-26 19:42 UTC, uN2RVw5q commented on contracts/v3/Vault.sol
>          _burn(msg.sender, _shares);
For the case when `_totalSupply` is `0`, the `_burn` will decrease the total supply, which will revert because of safemath. As long as `_shares > 0`.

2021-09-30 20:12 UTC, transferAndCall requested changes
I would flag this as a wont-fix. If `totalSupply()` is 0 there's nothing to withdraw anyway. The only thing this would change is the error message returned, but wouldn't affect the fact that the function still won't execute anyway.

2021-09-30 20:14 UTC, transferAndCall commented
This would only add more gas to valid withdraws with no change in the status of invalid (totalSupply = 0) withdraws.

2021-09-30 20:14 UTC, closed without merging